// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs
// Generated on: 2023.02.28 at 01:44:43 PM GET

package com.exactpro.sf.common.impl.messages.xml.configuration;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;extension base="{http://exactprosystems.com/dictionary}Field">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="field" type="{http://exactprosystems.com/dictionary}Field"/>
 *           &lt;element name="message" type="{http://exactprosystems.com/dictionary}Message"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "fieldsAndMessages"
})
public class Message
    extends Field
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElements({
        @XmlElement(name = "field"),
        @XmlElement(name = "message", type = Message.class)
    })
    protected List<Field> fieldsAndMessages;

    /**
     * Gets the value of the fieldsAndMessages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldsAndMessages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldsAndMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * {@link Message }
     * 
     * 
     */
    public List<Field> getFieldsAndMessages() {
        if (fieldsAndMessages == null) {
            fieldsAndMessages = new ArrayList<Field>();
        }
        return this.fieldsAndMessages;
    }

}
