// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs
// Generated on: 2023.02.28 at 01:44:43 PM GET

package com.exactpro.sf.common.impl.messages.xml.configuration;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.exactpro.sf.common.impl.messages.xml.configuration package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: com.exactpro.sf.common.impl.messages.xml.configuration
     */
    public ObjectFactory() {
    }

    /** Create an instance of {@link Dictionary.Fields } */
    public Dictionary.Fields createDictionaryFields() {
        return new Dictionary.Fields();
    }

    /** Create an instance of {@link Dictionary } */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /** Create an instance of {@link Message } */
    public Message createMessage() {
        return new Message();
    }

    /** Create an instance of {@link Dictionary.Messages } */
    public Dictionary.Messages createDictionaryMessages() {
        return new Dictionary.Messages();
    }

    /** Create an instance of {@link Attribute } */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /** Create an instance of {@link Field } */
    public Field createField() {
        return new Field();
    }

}
