//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 04:36:28 PM GET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://exactprosystems.com/dictionary", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.exactpro.sf.common.impl.messages.xml.configuration;
