// Autogenerated Jamon proxy
// src/main/templates/com/exactpro/sf/messages/impl/templates/ComplexFieldTypeTemplate.jamon

package com.exactpro.sf.messages.impl.templates;

import com.exactpro.sf.common.messages.structures.*;

@org.jamon.annotations.Template(
  signature = "B741F7C33C5EF79570E965CBE9DF8FD3",
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "distPackagePath", type = "String[]"),
    @org.jamon.annotations.Argument(name = "underscoreAsPackageSeparator", type = "boolean"),
    @org.jamon.annotations.Argument(name = "packageName", type = "String"),
    @org.jamon.annotations.Argument(name = "typeName", type = "String"),
    @org.jamon.annotations.Argument(name = "namespaceName", type = "String"),
    @org.jamon.annotations.Argument(name = "fields", type = "java.util.List<IFieldStructure>")})
public class ComplexFieldTypeTemplate
  extends org.jamon.AbstractTemplateProxy
{

  public ComplexFieldTypeTemplate(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }

  protected ComplexFieldTypeTemplate(String p_path)
  {
    super(p_path);
  }

  public ComplexFieldTypeTemplate()
  {
     super("/com/exactpro/sf/messages/impl/templates/ComplexFieldTypeTemplate");
  }

  public interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf
  {
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
  }

  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
    public void setDistPackagePath(String[] distPackagePath)
    {
      m_distPackagePath = distPackagePath;
    }
    public String[] getDistPackagePath()
    {
      return m_distPackagePath;
    }
    private String[] m_distPackagePath;
    public void setUnderscoreAsPackageSeparator(boolean underscoreAsPackageSeparator)
    {
      m_underscoreAsPackageSeparator = underscoreAsPackageSeparator;
    }
    public boolean getUnderscoreAsPackageSeparator()
    {
      return m_underscoreAsPackageSeparator;
    }
    private boolean m_underscoreAsPackageSeparator;
    public void setPackageName(String packageName)
    {
      m_packageName = packageName;
    }
    public String getPackageName()
    {
      return m_packageName;
    }
    private String m_packageName;

    public void setTypeName(String typeName)
    {
      m_typeName = typeName;
    }
    public String getTypeName()
    {
      return m_typeName;
    }
    private String m_typeName;

    public void setNamespaceName(String namespaceName)
    {
      m_namespaceName = namespaceName;
    }
    public String getNamespaceName()
    {
      return m_namespaceName;
    }
    private String m_namespaceName;

    public void setFields(java.util.List<IFieldStructure> fields)
    {
      m_fields = fields;
    }
    public java.util.List<IFieldStructure> getFields()
    {
      return m_fields;
    }
    private java.util.List<IFieldStructure> m_fields;
  }
  @Override
  protected org.jamon.AbstractTemplateProxy.ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }

  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }

  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new ComplexFieldTypeTemplateImpl(getTemplateManager(), getImplData());
  }

  public org.jamon.Renderer makeRenderer(final String[] distPackagePath, final boolean underscoreAsPackageSeparator, final String packageName, final String typeName, final String namespaceName, final java.util.List<IFieldStructure> fields)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, distPackagePath, underscoreAsPackageSeparator, packageName, typeName, namespaceName, fields);
      }
    };
  }

  public void render(final java.io.Writer jamonWriter, final String[] distPackagePath, final boolean underscoreAsPackageSeparator, final String packageName, final String typeName, final String namespaceName, final java.util.List<IFieldStructure> fields)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, distPackagePath, underscoreAsPackageSeparator, packageName, typeName, namespaceName, fields);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final String[] distPackagePath, final boolean underscoreAsPackageSeparator, final String packageName, final String typeName, final String namespaceName, final java.util.List<IFieldStructure> fields)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setDistPackagePath(distPackagePath);
    implData.setUnderscoreAsPackageSeparator(underscoreAsPackageSeparator);
    implData.setPackageName(packageName);
    implData.setTypeName(typeName);
    implData.setNamespaceName(namespaceName);
    implData.setFields(fields);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }

}
